Add a basic travis yaml file. Fixes for clang 3.8 stdlib.
Disable the recursive macro warnign which fires too frequently with
this stdlib. Remove the gsl::span-std::regex interoperability check test
since we don't use std::regex. Remove the noexcept specifier from
errno_exception: this is also incompatible with clang 3.8 stdlib.